### ISSUE TITLE
Iframe cannot allowed to access webcame and microphone

### ISSUE THREAD

**Issue by tampham47** [appearin/appearin.github.io#6]
Hi,
I am add appearin into my web application. It works well at localhost, but when deploy at server, it show a message that "We are not allowed to access your webcam and microphone".

![image](https://cloud.githubusercontent.com/assets/5687992/19136922/607bc168-8b9a-11e6-98bb-33c46e818c67.png)

I have tried to allow sandbox, but it still not work.

``` html
<iframe sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
    src="" id="js-appearin-iframe-holder"
    width="100%" height="100%" frameBorder="0"></iframe>
```

**Comment by vesper8** [comment]
@tampham47 did you figure it out? I'm having the same problem.. some answer would be much appreciated
